steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/postman-governance-grafana:latest'
  - '-f'
  - 'Dockerfile.grafana'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/postman-governance-grafana:latest'
