# Postman Governance Collector Configuration

# Data Collection Settings
collection:
  # Collection schedule (cron format)
  # Default: Every 6 hours at minute 0
  schedule: "0 */6 * * *"
  
  # Collection timeout in seconds
  timeout: 300
  
  # Maximum retries for failed collections
  max_retries: 3
  
  # Retry delay in seconds
  retry_delay: 60
  
  # Parallel collection workers
  workers: 2

# Database Settings
database:
  # SQLite database path (mounted volume)
  path: "/app/data/governance.db"
  
  # Backup settings
  backup:
    enabled: true
    retention_days: 30
    schedule: "0 2 * * *"  # Daily at 2 AM
    path: "/app/data/backups"
  
  # Database optimization
  wal_mode: true
  pragma_settings:
    synchronous: "NORMAL"
    cache_size: 10000
    temp_store: "MEMORY"
    journal_mode: "WAL"

# API Settings
api:
  # Server configuration
  port: 3001
  host: "0.0.0.0"
  
  # TLS/SSL configuration
  tls:
    enabled: false  # Set to true for HTTPS
    cert_file: "/app/certs/server.crt"
    key_file: "/app/certs/server.key"
    ca_file: "/app/certs/ca.crt"
    require_client_cert: false
  
  # Security settings
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst_limit: 20
    
    # Different limits for different endpoints
    endpoints:
      "/api/auth/login":
        requests_per_minute: 10
        burst_limit: 5
      "/api/collect":
        requests_per_minute: 5
        burst_limit: 2
      "/health":
        requests_per_minute: 300  # Health checks need higher limits
        burst_limit: 50
  
  # CORS settings
  cors:
    enabled: true
    origins: 
      - "http://localhost:3000"
      - "http://grafana:3000"
      - "http://postman-grafana:3000"
      - "https://*.company.com"  # Allow company domains
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization", "X-Requested-With", "X-API-Key"]
    credentials: true
    max_age: 86400  # 24 hours
  
  # Content security
  content_security:
    max_request_size: "10mb"
    max_json_size: "5mb"
    max_url_length: 2048
    parameter_limit: 1000
  
  # Request logging
  logging:
    enabled: true
    include_body: false
    include_headers: false
    include_auth_info: true
    include_response_time: true
    exclude_health_checks: true

# Postman API Settings
postman:
  # API configuration
  base_url: "https://api.getpostman.com"
  
  # Rate limiting (respect Postman's 300 req/min limit with safety buffer)
  rate_limit:
    requests_per_minute: 120
    burst_allowance: 5
  
  # Request settings
  timeout_seconds: 30
  max_retries: 3
  retry_backoff: 2
  
  # Data collection scope
  collection_scope:
    workspaces: true
    collections: true
    users: true
    environments: true
    monitors: true
    mocks: true
    api_specs: true
    user_groups: true
    private_apis: true
    workspace_tags: true
  
  # Collection limits (to prevent overwhelming the API)
  limits:
    max_collections_per_workspace: -1  # -1 means no limit, analyze all collections in workspace
    max_collection_analysis: -1  # -1 means no limit, analyze all collections for governance
    max_workspaces: -1  # -1 means no limit, analyze all workspaces

# Governance Calculation Settings
governance:
  # Scoring weights (must sum to 1.0)
  weights:
    documentation: 0.30
    testing: 0.25
    monitoring: 0.25
    organization: 0.20
  
  # Violation thresholds
  thresholds:
    critical_compliance_score: 60
    warning_compliance_score: 80
    max_fork_age_days: 90
    min_documentation_coverage: 80
    min_test_coverage: 70
  
  # Analysis settings
  analysis:
    include_private_apis: true
    include_workspace_tags: true
    deep_collection_analysis: true
    calculate_trends: true

# Security Settings
security:
  # Authentication configuration
  authentication:
    enabled: true
    methods: ["jwt", "api_key", "basic"]  # Supported auth methods
    default_method: "jwt"
    
    # JWT configuration
    jwt:
      secret: "${JWT_SECRET}"  # Must be set via environment variable
      algorithm: "HS256"
      expires_in: "24h"
      issuer: "postman-governance"
      audience: "governance-api"
    
    # Password policy
    password_policy:
      min_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special: true
      salt_rounds: 12
    
    # API key configuration
    api_keys:
      length: 32
      prefix: "PGSK-"
      default_expiration_days: 365
      rotation_warning_days: 30
    
    # Rate limiting for authentication
    rate_limiting:
      max_attempts: 5
      window_minutes: 15
      lockout_minutes: 30
  
  # Authorization configuration
  authorization:
    enabled: true
    
    # Role definitions
    roles:
      admin:
        description: "Full system access"
        permissions:
          - "governance:*"
          - "metrics:*"
          - "users:*"
          - "dashboard:*"
          - "export:*"
      analyst:
        description: "Data analysis access"
        permissions:
          - "governance:read"
          - "governance:analyze"
          - "metrics:read"
          - "dashboard:read"
          - "export:read"
      viewer:
        description: "Read-only access"
        permissions:
          - "governance:read"
          - "metrics:read"
          - "dashboard:read"
      service:
        description: "Programmatic access"
        permissions:
          - "governance:read"
          - "governance:write"
          - "metrics:read"
          - "metrics:write"
          - "api:*"
  
  # Session management
  sessions:
    enabled: true
    timeout_minutes: 480  # 8 hours
    cleanup_interval_minutes: 60
    max_concurrent_sessions: 5
  
  # API key handling
  api_key:
    rotation_warning_days: 30
    log_masked_key: true  # Only log last 4 characters
  
  # Data encryption
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_derivation: "PBKDF2"
    key_iterations: 100000
  
  # Security headers
  headers:
    enabled: true
    hsts: true  # HTTP Strict Transport Security
    csp: true   # Content Security Policy
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"
  
  # IP restrictions
  ip_filtering:
    enabled: false  # Set to true to enable IP whitelisting
    allowed_ips: []
    blocked_ips: []
    allow_private_networks: true
  
  # Audit logging
  audit:
    enabled: true
    log_level: "INFO"
    include_requests: true
    include_responses: false
    include_auth_events: true
    include_permission_checks: true
    retention_days: 90
    
  # Security monitoring
  monitoring:
    enabled: true
    failed_auth_threshold: 10
    suspicious_activity_detection: true
    alert_on_admin_actions: true
    alert_on_privilege_escalation: true

# Logging Settings
logging:
  # Log level (DEBUG, INFO, WARN, ERROR)
  level: "INFO"
  
  # Log format (json, text)
  format: "json"
  
  # Log destinations
  destinations:
    console: true
    file: true
    file_path: "/app/logs/governance-collector.log"
  
  # Log rotation
  rotation:
    enabled: true
    max_size_mb: 100
    max_files: 10
    max_age_days: 30
  
  # Security: Never log sensitive data
  security:
    mask_api_keys: true
    exclude_headers: ["authorization", "x-api-key"]
    exclude_sensitive_data: true

# Health Check Settings
health:
  # Health check endpoint configuration
  enabled: true
  path: "/health"
  
  # Health check components
  checks:
    database: true
    postman_api: true
    disk_space: true
    memory_usage: true
  
  # Thresholds for health warnings
  thresholds:
    disk_usage_percent: 85
    memory_usage_percent: 90
    api_response_time_ms: 5000

# Metrics and Monitoring
metrics:
  # Internal metrics
  enabled: true
  path: "/metrics"
  
  # Metrics collection
  collect:
    request_duration: true
    request_count: true
    error_count: true
    database_operations: true
    memory_usage: true
    collection_statistics: true
  
  # Metrics retention
  retention_hours: 168  # 7 days

# Feature Flags
features:
  # Enable/disable features
  historical_data_collection: true
  real_time_updates: false  # Future feature
  advanced_analytics: true
  data_export: true
  webhook_notifications: false  # Future feature
  
  # Security features
  multi_factor_auth: false  # Future feature
  sso_integration: false    # Future feature
  ldap_integration: false   # Future feature
  oauth2_provider: false    # Future feature
  
  # Compliance features
  gdpr_compliance: true
  audit_trail: true
  data_classification: true
  retention_policies: true
  
# Performance Settings
performance:
  # Worker pool settings
  worker_pool_size: 4
  queue_size: 1000
  
  # Memory limits
  max_memory_mb: 512
  gc_interval_minutes: 30
  
  # Connection pooling
  connection_pool:
    max_connections: 10
    idle_timeout_seconds: 300
    max_lifetime_seconds: 3600